#ifndef ABSTRACTSHAPE_GLOBAL_H
#define ABSTRACTSHAPE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABSTRACTSHAPE_LIBRARY)
#  define ABSTRACTSHAPESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ABSTRACTSHAPESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ABSTRACTSHAPE_GLOBAL_H
